project:
  type: website
  output-dir: docs
website:
  title: Blogs for my scholarly Observations using ML
  navbar:
    right:
      - Work from Home and cityscape.qmd
      - The Dataset used.qmd
      - About.qmd
      - icon: github
        href: 'https://github.com/'
      - icon: twitter
        href: 'https://twitter.com'
format:
  html:
    theme: cosmo
    css: styles.css
editor: visual

