project:
  type: website
  output-dir: docs
website:
  title: My Scholarly Observations
  navbar:
  
    right:
      - Work from Home and cityscape.qmd
      - Research Insights Explorer Using Machine learning.qmd
      - about.qmd
      
      - icon: github
        href: 'https://github.com/'
      - icon: twitter
        href: 'https://twitter.com'
format:
  html:
    theme: cosmo
    css: styles.css
editor: visual

